import { reactive } from 'vue';

export let store = reactive({
  home_visible: true,
  kana_visible: false,
  results_visible: false,
  hiragana_enabled: false,
  katakana_enabled: false,
  kana_count: 0,
  correct_count: 0,
  mistake_count: 0
});

export let options = reactive([
  {option: 'hiragana', kana: 'あいうえお', color: '#34d399', selected: true},
  {option: 'katakana', kana: 'アイウエオ', color: '#2b2d42', selected: false},
  {option: 'hiragana + katakana', kana: 'ひらがな　カタカナ', color: '#2b2d42', selected: false}
])

export let hiragana = reactive([
  {kana: 'あ', romaji: 'a', input: '', color: '#000', disabled: false},
  {kana: 'い', romaji: 'i', input: '', color: '#000', disabled: false},
  {kana: 'う', romaji: 'u', input: '', color: '#000', disabled: false},
  {kana: 'え', romaji: 'e', input: '', color: '#000', disabled: false},
  {kana: 'お', romaji: 'o', input: '', color: '#000', disabled: false},
  {kana: 'か', romaji: 'ka', input: '', color: '#000', disabled: false},
  {kana: 'き', romaji: 'ki', input: '', color: '#000', disabled: false},
  {kana: 'く', romaji: 'ku', input: '', color: '#000', disabled: false},
  {kana: 'け', romaji: 'ke', input: '', color: '#000', disabled: false},
  {kana: 'こ', romaji: 'ko', input: '', color: '#000', disabled: false},
  {kana: 'さ', romaji: 'sa', input: '', color: '#000', disabled: false},
  {kana: 'し', romaji: 'shi', input: '', color: '#000', disabled: false},
  {kana: 'す', romaji: 'su', input: '', color: '#000', disabled: false},
  {kana: 'せ', romaji: 'se', input: '', color: '#000', disabled: false},
  {kana: 'そ', romaji: 'so', input: '', color: '#000', disabled: false},
  {kana: 'た', romaji: 'ta', input: '', color: '#000', disabled: false},
  {kana: 'ち', romaji: 'chi', input: '', color: '#000', disabled: false},
  {kana: 'つ', romaji: 'tsu', input: '', color: '#000', disabled: false},
  {kana: 'て', romaji: 'te', input: '', color: '#000', disabled: false},
  {kana: 'と', romaji: 'to', input: '', color: '#000', disabled: false},
  {kana: 'な', romaji: 'na', input: '', color: '#000', disabled: false},
  {kana: 'に', romaji: 'ni', input: '', color: '#000', disabled: false},
  {kana: 'ぬ', romaji: 'nu', input: '', color: '#000', disabled: false},
  {kana: 'ね', romaji: 'ne', input: '', color: '#000', disabled: false},
  {kana: 'の', romaji: 'no', input: '', color: '#000', disabled: false},
  {kana: 'は', romaji: 'ha', input: '', color: '#000', disabled: false},
  {kana: 'ひ', romaji: 'hi', input: '', color: '#000', disabled: false},
  {kana: 'ふ', romaji: 'fu', input: '', color: '#000', disabled: false},
  {kana: 'へ', romaji: 'he', input: '', color: '#000', disabled: false},
  {kana: 'ほ', romaji: 'ho', input: '', color: '#000', disabled: false},
  {kana: 'ま', romaji: 'ma', input: '', color: '#000', disabled: false},
  {kana: 'み', romaji: 'mi', input: '', color: '#000', disabled: false},
  {kana: 'む', romaji: 'mu', input: '', color: '#000', disabled: false},
  {kana: 'め', romaji: 'me', input: '', color: '#000', disabled: false},
  {kana: 'も', romaji: 'mo', input: '', color: '#000', disabled: false},
  {kana: 'や', romaji: 'ya', input: '', color: '#000', disabled: false},
  {kana: 'ゆ', romaji: 'yu', input: '', color: '#000', disabled: false},
  {kana: 'よ', romaji: 'yo', input: '', color: '#000', disabled: false},
  {kana: 'ら', romaji: 'ra', input: '', color: '#000', disabled: false},
  {kana: 'り', romaji: 'ri', input: '', color: '#000', disabled: false},
  {kana: 'る', romaji: 'ru', input: '', color: '#000', disabled: false},
  {kana: 'れ', romaji: 're', input: '', color: '#000', disabled: false},
  {kana: 'ろ', romaji: 'ro', input: '', color: '#000', disabled: false},
  {kana: 'わ', romaji: 'wa', input: '', color: '#000', disabled: false},
  {kana: 'を', romaji: 'wo', input: '', color: '#000', disabled: false},
  {kana: 'ん', romaji: 'n', input: '', color: '#000', disabled: false},
  {kana: 'が', romaji: 'ga', input: '', color: '#000', disabled: false},
  {kana: 'ぎ', romaji: 'gi', input: '', color: '#000', disabled: false},
  {kana: 'ぐ', romaji: 'gu', input: '', color: '#000', disabled: false},
  {kana: 'げ', romaji: 'ge', input: '', color: '#000', disabled: false},
  {kana: 'ご', romaji: 'go', input: '', color: '#000', disabled: false},
  {kana: 'ざ', romaji: 'za', input: '', color: '#000', disabled: false},
  {kana: 'じ', romaji: 'ji', input: '', color: '#000', disabled: false},
  {kana: 'ず', romaji: 'zu', input: '', color: '#000', disabled: false},
  {kana: 'ぜ', romaji: 'ze', input: '', color: '#000', disabled: false},
  {kana: 'ぞ', romaji: 'zo', input: '', color: '#000', disabled: false},
  {kana: 'だ', romaji: 'da', input: '', color: '#000', disabled: false},
  {kana: 'ぢ', romaji: 'di', input: '', color: '#000', disabled: false},
  {kana: 'づ', romaji: 'du', input: '', color: '#000', disabled: false},
  {kana: 'で', romaji: 'de', input: '', color: '#000', disabled: false},
  {kana: 'ど', romaji: 'do', input: '', color: '#000', disabled: false},
  {kana: 'ば', romaji: 'ba', input: '', color: '#000', disabled: false},
  {kana: 'び', romaji: 'bi', input: '', color: '#000', disabled: false},
  {kana: 'ぶ', romaji: 'bu', input: '', color: '#000', disabled: false},
  {kana: 'べ', romaji: 'be', input: '', color: '#000', disabled: false},
  {kana: 'ぼ', romaji: 'bo', input: '', color: '#000', disabled: false},
  {kana: 'ぱ', romaji: 'pa', input: '', color: '#000', disabled: false},
  {kana: 'ぴ', romaji: 'pi', input: '', color: '#000', disabled: false},
  {kana: 'ぷ', romaji: 'pu', input: '', color: '#000', disabled: false},
  {kana: 'ぺ', romaji: 'pe', input: '', color: '#000', disabled: false},
  {kana: 'ぽ', romaji: 'po', input: '', color: '#000', disabled: false},
]);

export let katakana = reactive([
  {kana: 'ア', romaji: 'a', input: '', color: '#000', disabled: false},
  {kana: 'イ', romaji: 'i', input: '', color: '#000', disabled: false},
  {kana: 'ウ', romaji: 'u', input: '', color: '#000', disabled: false},
  {kana: 'エ', romaji: 'e', input: '', color: '#000', disabled: false},
  {kana: 'オ', romaji: 'o', input: '', color: '#000', disabled: false},
  {kana: 'カ', romaji: 'ka', input: '', color: '#000', disabled: false},
  {kana: 'キ', romaji: 'ki', input: '', color: '#000', disabled: false},
  {kana: 'ク', romaji: 'ku', input: '', color: '#000', disabled: false},
  {kana: 'ケ', romaji: 'ke', input: '', color: '#000', disabled: false},
  {kana: 'コ', romaji: 'ko', input: '', color: '#000', disabled: false},
  {kana: 'サ', romaji: 'sa', input: '', color: '#000', disabled: false},
  {kana: 'シ', romaji: 'shi', input: '', color: '#000', disabled: false},
  {kana: 'ス', romaji: 'su', input: '', color: '#000', disabled: false},
  {kana: 'セ', romaji: 'se', input: '', color: '#000', disabled: false},
  {kana: 'ソ', romaji: 'so', input: '', color: '#000', disabled: false},
  {kana: 'タ', romaji: 'ta', input: '', color: '#000', disabled: false},
  {kana: 'チ', romaji: 'chi', input: '', color: '#000', disabled: false},
  {kana: 'ツ', romaji: 'tsu', input: '', color: '#000', disabled: false},
  {kana: 'テ', romaji: 'te', input: '', color: '#000', disabled: false},
  {kana: 'ト', romaji: 'to', input: '', color: '#000', disabled: false},
  {kana: 'ナ', romaji: 'na', input: '', color: '#000', disabled: false},
  {kana: 'ニ', romaji: 'ni', input: '', color: '#000', disabled: false},
  {kana: 'ヌ', romaji: 'nu', input: '', color: '#000', disabled: false},
  {kana: 'ネ', romaji: 'ne', input: '', color: '#000', disabled: false},
  {kana: 'ノ', romaji: 'no', input: '', color: '#000', disabled: false},
  {kana: 'ハ', romaji: 'ha', input: '', color: '#000', disabled: false},
  {kana: 'ヒ', romaji: 'hi', input: '', color: '#000', disabled: false},
  {kana: 'フ', romaji: 'fu', input: '', color: '#000', disabled: false},
  {kana: 'ヘ', romaji: 'he', input: '', color: '#000', disabled: false},
  {kana: 'ホ', romaji: 'ho', input: '', color: '#000', disabled: false},
  {kana: 'マ', romaji: 'ma', input: '', color: '#000', disabled: false},
  {kana: 'ミ', romaji: 'mi', input: '', color: '#000', disabled: false},
  {kana: 'ム', romaji: 'mu', input: '', color: '#000', disabled: false},
  {kana: 'メ', romaji: 'me', input: '', color: '#000', disabled: false},
  {kana: 'モ', romaji: 'mo', input: '', color: '#000', disabled: false},
  {kana: 'ヤ', romaji: 'ya', input: '', color: '#000', disabled: false},
  {kana: 'ユ', romaji: 'yu', input: '', color: '#000', disabled: false},
  {kana: 'ヨ', romaji: 'yo', input: '', color: '#000', disabled: false},
  {kana: 'ラ', romaji: 'ra', input: '', color: '#000', disabled: false},
  {kana: 'リ', romaji: 'ri', input: '', color: '#000', disabled: false},
  {kana: 'ル', romaji: 'ru', input: '', color: '#000', disabled: false},
  {kana: 'レ', romaji: 're', input: '', color: '#000', disabled: false},
  {kana: 'ロ', romaji: 'ro', input: '', color: '#000', disabled: false},
  {kana: 'ワ', romaji: 'wa', input: '', color: '#000', disabled: false},
  {kana: 'ヲ', romaji: 'wo', input: '', color: '#000', disabled: false},
  {kana: 'ン', romaji: 'n', input: '', color: '#000', disabled: false},
  {kana: 'ガ', romaji: 'ga', input: '', color: '#000', disabled: false},
  {kana: 'ギ', romaji: 'gi', input: '', color: '#000', disabled: false},
  {kana: 'グ', romaji: 'gu', input: '', color: '#000', disabled: false},
  {kana: 'ゲ', romaji: 'ge', input: '', color: '#000', disabled: false},
  {kana: 'ゴ', romaji: 'go', input: '', color: '#000', disabled: false},
  {kana: 'ザ', romaji: 'za', input: '', color: '#000', disabled: false},
  {kana: 'ジ', romaji: 'ji', input: '', color: '#000', disabled: false},
  {kana: 'ズ', romaji: 'zu', input: '', color: '#000', disabled: false},
  {kana: 'ゼ', romaji: 'ze', input: '', color: '#000', disabled: false},
  {kana: 'ゾ', romaji: 'zo', input: '', color: '#000', disabled: false},
  {kana: 'ダ', romaji: 'da', input: '', color: '#000', disabled: false},
  {kana: 'ヂ', romaji: 'di', input: '', color: '#000', disabled: false},
  {kana: 'ヅ', romaji: 'du', input: '', color: '#000', disabled: false},
  {kana: 'デ', romaji: 'de', input: '', color: '#000', disabled: false},
  {kana: 'ド', romaji: 'do', input: '', color: '#000', disabled: false},
  {kana: 'バ', romaji: 'ba', input: '', color: '#000', disabled: false},
  {kana: 'ビ', romaji: 'bi', input: '', color: '#000', disabled: false},
  {kana: 'ブ', romaji: 'bu', input: '', color: '#000', disabled: false},
  {kana: 'ベ', romaji: 'be', input: '', color: '#000', disabled: false},
  {kana: 'ボ', romaji: 'bo', input: '', color: '#000', disabled: false},
  {kana: 'パ', romaji: 'pa', input: '', color: '#000', disabled: false},
  {kana: 'ピ', romaji: 'pi', input: '', color: '#000', disabled: false},
  {kana: 'プ', romaji: 'pu', input: '', color: '#000', disabled: false},
  {kana: 'ペ', romaji: 'pe', input: '', color: '#000', disabled: false},
  {kana: 'ポ', romaji: 'po', input: '', color: '#000', disabled: false},
]);
